# Generated by Django 2.2 on 2020-02-13 06:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_item_discount_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='description',
            field=models.TextField(default='This is bydefault text descption, entered at the time of migration from django developer'),
            preserve_default=False,
        ),
    ]
